services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: tasktool-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  sonarqube:
    image: sonarqube:community
    container_name: tasktool-sonarqube
    depends_on:
      - sqlserver
    ports:
      - "9000:9000"
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions
      - sonar_logs:/opt/sonarqube/logs

volumes:
  sqlserver_data:
  sonar_data:
  sonar_extensions:
  sonar_logs:
